[2024-09-30T12:09:13.239+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: supply_app_dag.scrapper_duckdb scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-09-30T12:09:13.262+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: supply_app_dag.scrapper_duckdb scheduled__2024-09-29T00:00:00+00:00 [queued]>
[2024-09-30T12:09:13.263+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-30T12:09:13.301+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): scrapper_duckdb> on 2024-09-29 00:00:00+00:00
[2024-09-30T12:09:13.315+0000] {standard_task_runner.py:60} INFO - Started process 190 to run task
[2024-09-30T12:09:13.326+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'supply_app_dag', 'scrapper_duckdb', 'scheduled__2024-09-29T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/supply_chain_dag.py', '--cfg-path', '/tmp/tmpa3fbiedh']
[2024-09-30T12:09:13.337+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask scrapper_duckdb
[2024-09-30T12:09:13.378+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-30T12:09:13.483+0000] {task_command.py:423} INFO - Running <TaskInstance: supply_app_dag.scrapper_duckdb scheduled__2024-09-29T00:00:00+00:00 [running]> on host 0af04ae79775
[2024-09-30T12:09:13.703+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='supply_app_dag' AIRFLOW_CTX_TASK_ID='scrapper_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2024-09-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-29T00:00:00+00:00'
[2024-09-30T12:09:13.708+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-30T12:09:13.711+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/scrapper_duckdb.py']
[2024-09-30T12:09:13.747+0000] {subprocess.py:86} INFO - Output:
[2024-09-30T12:09:13.832+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/scripts/scrapper_duckdb.py': [Errno 2] No such file or directory
[2024-09-30T12:09:13.839+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-09-30T12:09:13.865+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-09-30T12:09:13.875+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=supply_app_dag, task_id=scrapper_duckdb, execution_date=20240929T000000, start_date=20240930T120913, end_date=20240930T120913
[2024-09-30T12:09:13.912+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task scrapper_duckdb (Bash command failed. The command returned a non-zero exit code 2.; 190)
[2024-09-30T12:09:13.939+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-30T12:09:13.997+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
